name: CI

on:
  push:
    branches:
      - main
      - dev

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Remote tests
        run: |
          BRANCH=${{ github.ref_name }}
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.PIPELINE_TRIGGER_TOKEN }}" \
          https://api.github.com/repos/amsterdamtimemachine/amsterdam-diaries/dispatches \
          -d '{"event_type": "trigger-action", "client_payload": {"branchs": "'"$BRANCH"'"}}'
